apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-htba
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-ktga-tenant/rhtap-demo-app/hacbs-test-project-htba@sha256:3d686cb48de0a38a5061da5e635a8492ee877c9dea9170956cfd2aee590faa6a
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
